name: hybrid_wssd
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - liblzma=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.1=h7b32b05_0
  - pip=25.0.1=pyh8b19718_0
  - python=3.10.16=he725a3c_1_cpython
  - readline=8.2=h8c095d6_2
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.15
      - aiosignal==1.3.2
      - antlr4-python3-runtime==4.9.3
      - asteroid-filterbanks==0.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - auraloss==0.4.0
      - beautifulsoup4==4.13.4
      - bottleneck==1.4.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.1
      - ci-sdr==0.0.2
      - click==8.1.8
      - configargparse==1.7
      - contourpy==1.3.1
      - ctc-segmentation==1.7.4
      - cycler==0.12.1
      - cython==3.2.1
      - datetime==5.5
      - decorator==5.2.1
      - distance==0.1.3
      - docstring-parser==0.16
      - editdistance==0.8.1
      - einops==0.8.1
      - espnet==202412
      - espnet-tts-frontend==0.0.3
      - fast-bss-eval==0.1.3
      - ffmpeg-python==0.2.0
      - filelock==3.18.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.3.2
      - g2p-en==2.1.0
      - git+https://github.com/detly/gammatone
      - grpcio==1.71.0
      - h5py==3.13.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - hyperpyyaml==1.2.2
      - idna==3.10
      - importlib-metadata==4.13.0
      - importlib-resources==6.5.2
      - inflect==7.5.0
      - jaconv==0.4.0
      - jamo==0.4.1
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonargparse==4.38.0
      - kaldiio==2.18.1
      - kiwisolver==1.4.8
      - librosa==0.9.2
      - lightning==2.5.1
      - lightning-utilities==0.14.2
      - llvmlite==0.43.0
      - markdown==3.7
      - markupsafe==3.0.2
      - mat73==0.65
      - matplotlib==3.10.1
      - mock==5.2.0
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - multidict==6.3.0
      - nara-wpe==0.0.11
      - netcdf4==1.7.2
      - networkx==3.4.2
      - nltk==3.9.1
      - nnaudio==0.3.3
      - nose==1.3.7
      - numba==0.60.0
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - packaging==24.2
      - pandas==2.2.3
      - pesq==0.0.4
      - pillow==11.2.1
      - platformdirs==4.3.7
      - pooch==1.8.2
      - propcache==0.3.1
      - protobuf==6.30.2
      - pybind11==3.0.1
      - pycparser==2.22
      - pyloudnorm==0.1.1
      - pyparsing==3.2.3
      - pypinyin==0.44.0
      - pyroomacoustics==0.8.6
      - pysocks==1.7.1
      - pystoi==0.4.1
      - python-dateutil==2.9.0.post0
      - python-sofa==0.2.0
      - pytorch-lightning==2.5.1
      - pytz==2025.2
      - pyworld==0.3.5
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - resampy==0.4.3
      - rotary-embedding-torch==0.8.6
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - safetensors==0.7.0
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentencepiece==0.1.97
      - setuptools==73.0.1
      - six==1.17.0
      - soundfile==0.13.1
      - soupsieve==2.7
      - soxr==1.0.0
      - speechbrain==1.0.2
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.6.0
      - torch-complex==0.4.4
      - torchaudio==2.6.0
      - torchinfo==1.8.0
      - torchmetrics==1.7.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.2.0
      - typeguard==4.4.2
      - typeshed-client==2.7.0
      - typing-extensions==4.13.0
      - tzdata==2025.2
      - unidecode==1.3.8
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - yarl==1.18.3
      - zipp==3.21.0
      - zope-interface==7.2
